ServerEvents.recipes(event => {
    //速度饰品
    event.shaped(Item.of('xmsm:speed1'),
    [
        'ABA',
        'BCB',
        'ADA'
    ],
    {
        A:'minecraft:feather',
        B:'minecraft:diamond_block',
        C:'enigmaticlegacy:iron_ring',
        D:'minecraft:netherite_ingot'
    })
    event.shaped(Item.of('xmsm:speed2'),
    [
        'ABA',
        'BCB',
        'ABA'
    ],
    {
        A:'minecraft:phantom_membrane',
        B:'minecraft:netherite_ingot',
        C:'xmsm:speed1'
    })
    event.shaped(Item.of('xmsm:speed3'),
    [
        'ABA',
        'BCB',
        'ADA'
    ],
    {
        A:'enigmaticlegacy:etherium_nugget',
        B:'enigmaticlegacy:astral_dust',
        C:'xmsm:speed2',
        D:'enigmaticlegacy:evil_ingot'
    })
    
//手变长饰品
    event.shaped(Item.of('xmsm:grip1'),
    [
        'ABA',
        'DCE',
        'ABA'
    ],
    {
        A:'minecraft:gold_ingot',
        B:'minecraft:fishing_rod',
        C:'enigmaticlegacy:iron_ring',
        D:'minecraft:heart_of_the_sea',
        E:'iceandfire:witherbone'
    })

    event.shaped(Item.of('xmsm:grip2'),
    [
        'ABC',
        'DED',
        'FBG'
    ],
    {
        A:'enigmaticlegacy:magnet_ring',
        B:'minecraft:diamond',
        C:'enigmaticlegacy:ender_ring',
        D:'minecraft:echo_shard',
        E:'xmsm:grip1',
        F:'enigmaticlegacy:earth_heart',
        G:'minecraft:ender_pearl'
    })

    event.shaped(Item.of('xmsm:grip3'),
    [
        'ABC',
        'DED',
        'FBG'
    ],
    {
        A:'enigmaticlegacy:cosmic_heart',
        B:'enigmaticlegacy:evil_ingot',
        C:'minecraft:nether_star',
        D:'mutantmonsters:endersoul_hand',
        E:'xmsm:grip2',
        F:'enigmaticlegacy:twisted_heart',
        G:'enigmaticlegacy:abyssal_heart'
    })
})